#!/bin/bash
clear
CWD="$(dirname $0)";
cd $CWD
echo "============================================"
echo "Installing the bundler gem"
echo "============================================"
GEM="$(which gem)";
$GEM install bundler
echo "============================================"
echo "Running Bundler"
echo "============================================"
BUNDLER="$(which bundle)";
$BUNDLER install --gemfile=$CWD/Gemfile
echo "============================================"
echo "Installing CocoaPods"
echo "============================================"
POD="$(which pod)";
$POD install --project-directory=$CWD
echo "============================================"
echo "Changing bundle identifiers"
echo "============================================"
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.getfetchapp.Fetch-$(date +%s)" $CWD/Fetch/Info.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.getfetchapp.PutioKit-$(date +%s)" $CWD/PutioKit/Info.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.getfetchapp.SRBarcodeScanner-$(date +%s)" $CWD/SRBarcodeScanner/Info.plist
echo "============================================"
echo "Fetch is ready to build! 🚀"
echo "============================================"
