#!/bin/bash
clear
echo "============================================"
echo "Installing the bundler gem"
echo "============================================"
gem install bundle
echo "============================================"
echo "Running Bundler"
echo "============================================"
bundle install
echo "============================================"
echo "Installing CocoaPods"
echo "============================================"
bundle exec pod install
echo "============================================"
echo "Changing bundle identifiers"
echo "============================================"
sed -i -e 's/com.getfetchapp.Fetch/com.getfetchapp.Fetch-'$(date +%s)'/g' Fetch.xcodeproj/project.pbxproj
sed -i -e 's/com.getfetchapp.PutioKit/com.getfetchapp.PutioKit-'$(date +%s)'/g' Fetch.xcodeproj/project.pbxproj
sed -i -e 's/com.getfetchapp.SRBarcodeScanner/com.getfetchapp.SRBarcodeScanner-'$(date +%s)'/g' Fetch.xcodeproj/project.pbxproj
echo "============================================"
echo "Fetch is ready to build! 🚀"
echo "============================================"
